spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/test-db
    username: test-user
    password: test-password
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

application:
  security:
    jwt:
      secret-key: 404E635266556A586E327AWSDD21282F413F4428472B4B6250645367566B5970
      expiration: 30000 # 1 min
      refresh-token:
        expiration: 60000 # 1 min

#server:
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: ah64apache
#    key-store-type: PKCS12
#    key-alias: stockbackend
#  port: 5050